project:
  type: website

website:
  title: "Erin Wang Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-heart-fill
      - href: projects.qmd
        text: Work Experience + Academic Projects
        icon: mortarboard-fill
      - href: research.qmd
        text: Research
        icon: pen-fill
      - href: personalproj.qmd
        text: Personal Projects
        icon: person-heart
      - href: leadership.qmd
        text: Leadership
        icon: people-fill

      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    math:
      method: mathjax
      options:
        autoNumber: "AMS"
      citations: true
    link-external-icon: true
    code-line-numbers: true




