---
title: "Biophotonics Lab"
description: "Research on the Monitoring the Rhizosphere Project to map root systems using low-coherence interferometry."
author: "Erin Wang"
date-start: "May 2024"
date-end: "Present"
advisor: "Professor Joshua Brake"
collaborators: "Grey Seymour, Audrey Gruian"
categories:
  - biophotonics
  - optics
  - python programming
  - data analysis
draft: false
---
## Motivation
The [Biophotonics Lab](https://pages.hmc.edu/biophotonics/) at Harvey Mudd College focuses on building optical tools for applications in biomedicine and agriculture.

The [Rhizosphere project](https://pages.hmc.edu/biophotonics/projects/rhizosphere/) is working on designing an optical tool that can non-invasively map out root systems and possibly characterize root health using the light-piping properties of plant stems. The project's scope revolves around evaluating the ability of low coherence interferometry in producing depth scans of the *Arabidopsis Thaliana* root *in situ*. 

## Research Work
My role on the Rhizosphere project mainly involves designing, building, aligning, and testing the optical systems including automating data collection. My inital work on the project (2024) was to build a system that could image a mung bean stem and measure light transmission through the stem. With my lab partner, Audrey Gruian, I constructed a USB camera microscope that magnified the mung bean stem enough to visualize the stem's hollow center. We were able to take images of the mung bean stem using this apparatus. 

I then worked on a mung bean "cage" setup to measure light transmission through the stem by feeding red He-Ne laser light into the stem by way of an optical fiber and capturing the transmitted light with a photodetector. Through this setup, we were able to measure changes in transmission across mung beans of different length as well as visualize the drop off of transmission as the stem wilts. 

(Insert picture of setup and data)

This past summer (2025), I worked with Grey Seymour on moving towards measuring backscatter rather than transmission and towards using *Arabidopsis Thaliana* instead of mung beans for its applicability to a wide range of flowering plants. I first started by building an interferometer with an electrical optical modulator (EOM) to manipulate the phase of the reference wave. I wrote a Python program using the `nidaqmx` package to capture the data from our data acquistion device and fit the curve to the expected sinusoidal interference equation.

However, due to the sensitivity of our system to miniscule changes in the environment (e.g. slight table movement, activity from the other lab members, etc.), the wide variability of the results proved inconclusive in verifying the EOM interferometry setup. We decided to move towards a low coherence interferometer (LCI) setup to preserve a high resolution in measurements while limiting the sensitivity to environmental variables. Towards the end of the summer, I wrote a Python script on Colab to simulate and understand the expected interference pattern and coherence length of a monochrome (single wavelength) source versus a broadband source. Then, I designed, built, and aligned an LCI interferometer with a near-infrared super luminescent diode as its broadband source. The end of the summer was the beginning of attempting to verify the LCI setup using a TIR retroreflector as the sample. I wrote a program incorporating the `nidaqmx` and `pylablib` packages to automate collecting data while moving the reference mirror stage.  

(insert picture of setup)

We are currently still working on taking this verification data due to challenges with capturing the whole range of the reference mirror stage. We hope to finish verifying the LCI setup and move to implementing the Arabidopsis stem to present for the SPIE conference in the Spring. 

## Documentation
Daily lab notebooks were kept on Confluence along with a weekly summary and all lab notebooks linked on a parent page. Each lab notebook contained a checklist of action items for the day, a section for what was completed that day/where we were stuck/what action items were planned for the next day, and a section for detailed documentation of our work that day. Weekly summaries included what was achieved that week and what goals we were setting for the next week. I learned greatly in this lab how important documentation can be especially when reproducing lab setups and revisiting results. I also worked with a different lab partner my second summer in the lab. The daily lab notebooks were incredible handy in onboarding the new member. 

In addition to daily lab notebooks, over the summer terms we had two presentations we gave to the rest of the research groups in the program as well as a summary of our summer progress in a white paper and a poster. The poster was presented at a gallery walk in front of the school where students and staff could ask about our experience and research in the lab. 

(insert picture of poster presentation)

## White Paper Links

[Summer 2025 Research Report](https://erinlywang.github.io/rhizo-report-2025/)
Summer 2024 Research Report

## Acknowledgements
I want to acknowledge my advisor Professor Brake for his incredible mentorship and for the opportunities he gave me to make the research my own. I got to lead and mold the project to to incorporate skills I had always wanted to learn or strengthen. I also want to acknowledge my incredible research team for creating an environment that I looked forward to coming to every day. And lastly, an acknowledgement to Harvey Mudd and the resources they provide to us students to be able to conduct research under close advising from our professors. I am extremely grateful for the research experiences I've been able to have here at Harvey Mudd. 