---
title: "YAPA Kids"
description: "Worked on the executive board of an international non-profit teaching organization as the Director of HR."
author: "Erin Wang"
subtitle: "May 2020 - June 2022"
enddate: 2022-06-01
categories:
  - Director of HR
  - Non-profit
  - Teaching
draft: false
---

At the peak of the pandemic, I joined YAPA Kids, an international non-profit organization. As the Director of HR, My position revolved mainly around recruitment byleading a team to filter applicants, host interviews, and onboard new members. When YAPA kids was just beginning, our team was a small group of three, but one night the program skyrocketed in applications from only 20 to 30 applications at a time to thousands of applications. The sudden influx of applicants posed a serious challenge. I expanded my team with more dedicated program volunteers, but we could barely make a dent in the mountain of applications. Stepping further into my director role, I developed a completely new holistic application process with my team to fairly evaluate each applicant and effectively find those committed to the program's mission with reasonable application response time. With the new application framework the program was able to oversee more than 600 passionate volunteers. 
 